// Public exports for @kamel/shared — event schemas, metrics types, and parseEvent.

export {
  BaseEventSchema,
  AnyEventSchema,
  UserSignedUpEventSchema,
  RideSearchedEventSchema,
  RideRequestedEventSchema,
  RideMatchedEventSchema,
  RideAcceptedEventSchema,
  RideCancelledEventSchema,
  RideCompletedEventSchema,
  DriverRatedEventSchema,
  PostCreatedEventSchema,
  MessageSentEventSchema,
  parseEvent,
} from "./events.js";

export type {
  BaseEvent,
  AnyEvent,
  UserSignedUpEvent,
  RideSearchedEvent,
  RideRequestedEvent,
  RideMatchedEvent,
  RideAcceptedEvent,
  RideCancelledEvent,
  RideCompletedEvent,
  DriverRatedEvent,
  PostCreatedEvent,
  MessageSentEvent,
  ParseEventResult,
  ParseEventSuccess,
  ParseEventFailure,
} from "./events.js";

export {
  IsoDateParamSchema,
  MetricsRangeQuerySchema,
  MetricsSummarySchema,
  FunnelStepNameSchema,
  FunnelStepSchema,
  MetricsFunnelSchema,
  TimeseriesGranularitySchema,
  EventTypeFilterSchema,
  MetricsTimeseriesQuerySchema,
  TimeseriesPointSchema,
  MetricsTimeseriesSchema,
  MetricsRoutesQuerySchema,
  RouteStatSchema,
  MetricsRoutesSchema,
  HeatmapCellSchema,
  MetricsHeatmapSchema,
  DeadLetterItemSchema,
  MetricsPipelineHealthSchema,
} from "./metrics.js";

export type {
  MetricsRangeQuery,
  MetricsSummary,
  FunnelStepName,
  FunnelStep,
  MetricsFunnel,
  TimeseriesGranularity,
  MetricsTimeseriesQuery,
  TimeseriesPoint,
  MetricsTimeseries,
  MetricsRoutesQuery,
  RouteStat,
  MetricsRoutes,
  HeatmapCell,
  MetricsHeatmap,
  DeadLetterItem,
  MetricsPipelineHealth,
} from "./metrics.js";
